/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examination;

import java.awt.Dimension;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class Examination extends javax.swing.JFrame {

    /**
     * Creates new form Examination
     */
    DbConnection db;
    public Examination() throws ClassNotFoundException, SQLException {
        initComponents();
        this.db = new DbConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        rdoOption4 = new javax.swing.JRadioButton();
        rdoOption1 = new javax.swing.JRadioButton();
        rdoOption2 = new javax.swing.JRadioButton();
        rdoOption3 = new javax.swing.JRadioButton();
        btnSubmit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNext.setBackground(new java.awt.Color(102, 153, 255));
        btnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 90, 40));

        btnPrevious.setBackground(new java.awt.Color(102, 153, 255));
        btnPrevious.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("Previous");
        jPanel1.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 90, 40));

        lblQuestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuestion.setText("Question");
        jPanel1.add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, 40));

        rdoOption4.setBackground(new java.awt.Color(204, 204, 204));
        rdoOption4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoOption4.setText("Option 4");
        jPanel1.add(rdoOption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 210, 40));

        rdoOption1.setBackground(new java.awt.Color(204, 204, 204));
        rdoOption1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoOption1.setText("Option 1");
        jPanel1.add(rdoOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, 40));

        rdoOption2.setBackground(new java.awt.Color(204, 204, 204));
        rdoOption2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoOption2.setText("Option 2");
        rdoOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoOption2ActionPerformed(evt);
            }
        });
        jPanel1.add(rdoOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, 40));

        rdoOption3.setBackground(new java.awt.Color(204, 204, 204));
        rdoOption3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoOption3.setText("Option 3");
        jPanel1.add(rdoOption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 900, 480));

        btnSubmit1.setBackground(new java.awt.Color(102, 153, 255));
        btnSubmit1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSubmit1.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit1.setText("Submit");
        getContentPane().add(btnSubmit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 600, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoOption2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoOption2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            data();
            Object row[] = (Object[])questions.get(0);
            lblQuestion.setText(row[0].toString());
            
        } catch (SQLException ex) {
            Logger.getLogger(Examination.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened
    
    ArrayList questions;
    @SuppressWarnings("empty-statement")
    private void data() throws SQLException
    {
        String query = "select * from Questions";
        ResultSet rs = db.stm.executeQuery(query);
        while(rs.next())
        {
            Object row[] = {rs.getString("Questions")};
            questions.add(row);
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Examination().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(Examination.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JRadioButton rdoOption1;
    private javax.swing.JRadioButton rdoOption2;
    private javax.swing.JRadioButton rdoOption3;
    private javax.swing.JRadioButton rdoOption4;
    // End of variables declaration//GEN-END:variables
}
