/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examination;

/**
 *
 * @author User
 */
public class StudentDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashBoard
     */
    public StudentDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGreeting = new javax.swing.JLabel();
        lblBatch = new javax.swing.JLabel();
        lblStudentName1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnGiveExam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGreeting.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGreeting.setText("Welcome ,");
        getContentPane().add(lblGreeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 60, -1, 32));

        lblBatch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBatch.setText("Batch");
        getContentPane().add(lblBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 134, -1, 35));

        lblStudentName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStudentName1.setText("Student Name");
        getContentPane().add(lblStudentName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 93, -1, 35));

        label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label.setText("Batch :");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 134, -1, 35));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subjects", "Set", "Mark Obtained"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 410, 90));

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 96, 35));

        btnGiveExam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGiveExam.setText("Give Exam");
        btnGiveExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveExamActionPerformed(evt);
            }
        });
        getContentPane().add(btnGiveExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 96, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnGiveExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveExamActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnGiveExamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGiveExam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblStudentName1;
    // End of variables declaration//GEN-END:variables
}
